apiVersion: v1
kind: PodTemplate
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    upm.io/owner: upm
    type: mysql-router
    edition: community
    version: {{ .Chart.AppVersion | quote }}
template:
  metadata:
    annotations:
      kubectl.kubernetes.io/default-container: mysql-router
    labels:
      type: mysql-router
      edition: community
      version: {{ .Chart.AppVersion | quote }}
  spec:
    tolerations:
      - key: "key"
        operator: "Equal"
        value: "value"
        effect: "NoSchedule"
    dnsPolicy: ClusterFirst
    restartPolicy: Always
    terminationGracePeriodSeconds: 30
    securityContext:
      fsGroup: 1001
      fsGroupChangePolicy: OnRootMismatch
    initContainers:
      - name: init-container
        image: {{ include "router.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        securityContext:
          runAsUser: 1001
          runAsGroup: 1001
          allowPrivilegeEscalation: false
        command:
          - "bash"
          - "-c"
          - "service-ctl.sh initialize"
        env:
          - name: DATA_MOUNT
            valueFrom:
              fieldRef:
                apiVersion: "v1"
                fieldPath: "metadata.annotations['unit-operator/storage.volume.data.mountPath']"
          - name: LOG_MOUNT
            valueFrom:
              fieldRef:
                apiVersion: "v1"
                fieldPath: "metadata.annotations['unit-operator/storage.volume.log.mountPath']"
          - name: SECRET_MOUNT
            valueFrom:
              fieldRef:
                apiVersion: "v1"
                fieldPath: "metadata.annotations['unit-operator/extraVolume.volume.unit-secret.volumeMountPath']"
          - name: DATA_DIR
            value: "$(DATA_MOUNT)/data"
          - name: CONF_DIR
            value: "$(DATA_MOUNT)/conf"
          - name: SERVICE_GROUP_NAME
            valueFrom:
              fieldRef:
                apiVersion: "v1"
                fieldPath: "metadata.labels['upm.api/service-group.name']"
          - name: AES_SECRET_KEY
            valueFrom:
              secretKeyRef:
                key: AES_SECRET_KEY
                name: aes-secret-key
      - name: sysctl
        image: {{ include "router.image" . }}
        command:
          - "bash"
          - "-c"
          - "ulimit -n 65535"
        securityContext:
          privileged: true
          runAsUser: 0
    containers:
      - name: mysql-router
        image: {{ include "router.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        securityContext:
          runAsUser: 1001
          runAsGroup: 1001
          allowPrivilegeEscalation: false
        ports:
          - containerPort: 6446
            name: mysql-router
          - containerPort: 6447
            name: mysqlx-router
        env:
          - name: DATA_MOUNT
            valueFrom:
              fieldRef:
                apiVersion: "v1"
                fieldPath: "metadata.annotations['unit-operator/storage.volume.data.mountPath']"
          - name: LOG_MOUNT
            valueFrom:
              fieldRef:
                apiVersion: "v1"
                fieldPath: "metadata.annotations['unit-operator/storage.volume.log.mountPath']"
          - name: SECRET_MOUNT
            valueFrom:
              fieldRef:
                apiVersion: "v1"
                fieldPath: "metadata.annotations['unit-operator/extraVolume.volume.unit-secret.volumeMountPath']"
          - name: DATA_DIR
            value: "$(DATA_MOUNT)/data"
          - name: CONF_DIR
            value: "$(DATA_MOUNT)/conf"
          - name: SERVICE_GROUP_NAME
            valueFrom:
              fieldRef:
                apiVersion: "v1"
                fieldPath: "metadata.labels['upm.api/service-group.name']"
          - name: HTTP_PORT
            value: "8081"
          - name: AES_SECRET_KEY
            valueFrom:
              secretKeyRef:
                key: AES_SECRET_KEY
                name: aes-secret-key
        livenessProbe:
          exec:
            command:
              - "timeout"
              - "3"
              - "bash"
              - "-c"
              - "</dev/tcp/localhost/9001"
          failureThreshold: 3
          initialDelaySeconds: 12
          periodSeconds: 12
          timeoutSeconds: 4
          successThreshold: 1
        readinessProbe:
          exec:
            command:
              - "timeout"
              - "3"
              - "bash"
              - "-c"
              - "service-ctl.sh health"
          failureThreshold: 3
          initialDelaySeconds: 12
          periodSeconds: 12
          timeoutSeconds: 4
          successThreshold: 1
        startupProbe:
          exec:
            command:
              - "timeout"
              - "3"
              - "bash"
              - "-c"
              - "</dev/tcp/localhost/9001"
          failureThreshold: 3
          initialDelaySeconds: 12
          periodSeconds: 12
          timeoutSeconds: 4
          successThreshold: 1
      - name: unit-agent
        image: {{ include "router.agent.image" . }}
        imagePullPolicy: {{ .Values.agent.image.pullPolicy | quote }}
        securityContext:
          runAsUser: 1001
          runAsGroup: 1001
          allowPrivilegeEscalation: false
        ports:
          - containerPort: 2214
            name: unit-agent
        env:
          - name: UNIT_TYPE
            valueFrom:
              fieldRef:
                apiVersion: "v1"
                fieldPath: "metadata.annotations['kubectl.kubernetes.io/default-container']"
          - name: DATA_MOUNT
            valueFrom:
              fieldRef:
                apiVersion: "v1"
                fieldPath: "metadata.annotations['unit-operator/storage.volume.data.mountPath']"
          - name: LOG_MOUNT
            valueFrom:
              fieldRef:
                apiVersion: "v1"
                fieldPath: "metadata.annotations['unit-operator/storage.volume.log.mountPath']"
          - name: DATA_DIR
            value: "$(DATA_MOUNT)/data"
          - name: CONF_DIR
            value: "$(DATA_MOUNT)/conf"
          - name: CONFIG_PATH
            value: "$(DATA_MOUNT)/conf/mysqlrouter.conf"
          - name: SERVICE_GROUP_NAME
            valueFrom:
              fieldRef:
                apiVersion: "v1"
                fieldPath: "metadata.labels['upm.api/service-group.name']"
          - name: UNIT_SN
            valueFrom:
              fieldRef:
                apiVersion: "v1"
                fieldPath: "metadata.labels['unit-operator/unit.sn']"
          - name: MYSQL_ROUTER_PORT
            value: "6446"
          - name: MYSQLX_ROUTER_PORT
            value: "6447"
          - name: HTTP_PORT
            value: "8081"
          - name: AES_SECRET_KEY
            valueFrom:
              secretKeyRef:
                key: AES_SECRET_KEY
                name: aes-secret-key
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
